framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: true
    handle_all_throwables: true
    session:
        handler_id: null
        save_path: '%env(resolve:UPLOAD_DIR)%/.sessions'
        cookie_secure: auto
        cookie_samesite: lax
        gc_maxlifetime: 86400
    php_errors:
        log: true
    assets: ~
