<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260508110120 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, slug VARCHAR(220) NOT NULL, category VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, event_date DATE DEFAULT NULL, location VARCHAR(100) DEFAULT NULL, cover_image VARCHAR(255) DEFAULT NULL, status VARCHAR(20) NOT NULL, sort_order INT NOT NULL, featured BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2FB3D0EE989D9B62 ON project (slug)');
        $this->addSql('CREATE TABLE project_photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, original_filename VARCHAR(255) NOT NULL, stored_filename VARCHAR(255) NOT NULL, path VARCHAR(500) NOT NULL, extension VARCHAR(10) DEFAULT NULL, file_size INT DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, caption VARCHAR(200) DEFAULT NULL, sort_order INT NOT NULL, is_cover BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7E28D86166D1F9C ON project_photo (project_id)');
        $this->addSql('ALTER TABLE project_photo ADD CONSTRAINT FK_7E28D86166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE project_photo DROP CONSTRAINT FK_7E28D86166D1F9C');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE project_photo');
    }
}
