<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260609085640 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajout des champs auth sur Client + création de password_reset_token';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE password_reset_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(100) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6B7BA4B65F37A13B ON password_reset_token (token)');
        $this->addSql('CREATE INDEX IDX_6B7BA4B619EB6921 ON password_reset_token (client_id)');
        $this->addSql('ALTER TABLE password_reset_token ADD CONSTRAINT FK_6B7BA4B619EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE client ADD password VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE client ADD last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE client ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE client ADD roles JSON DEFAULT \'["ROLE_CLIENT"]\' NOT NULL');
        $this->addSql('UPDATE client SET roles = \'["ROLE_CLIENT"]\' WHERE roles IS NULL');
        $this->addSql('ALTER TABLE client ALTER COLUMN roles DROP DEFAULT');
        $this->addSql('ALTER TABLE client ADD is_active BOOLEAN DEFAULT TRUE NOT NULL');
        $this->addSql('ALTER TABLE client ALTER COLUMN is_active DROP DEFAULT');
        $this->addSql('ALTER TABLE client ADD is_verified BOOLEAN DEFAULT FALSE NOT NULL');
        $this->addSql('ALTER TABLE client ALTER COLUMN is_verified DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE password_reset_token DROP CONSTRAINT FK_6B7BA4B619EB6921');
        $this->addSql('DROP TABLE password_reset_token');
        $this->addSql('ALTER TABLE client DROP password');
        $this->addSql('ALTER TABLE client DROP roles');
        $this->addSql('ALTER TABLE client DROP is_active');
        $this->addSql('ALTER TABLE client DROP is_verified');
        $this->addSql('ALTER TABLE client DROP last_login_at');
        $this->addSql('ALTER TABLE client DROP updated_at');
    }
}
