<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260508120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Création des tables user, client, gallery, photo';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');

        $this->addSql('CREATE TABLE client (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, phone VARCHAR(20) DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C7440455E7927C74 ON client (email)');

        $this->addSql('CREATE TABLE gallery (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_id INT NOT NULL, title VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, access_code VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, session_date DATE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, view_count INT NOT NULL, last_access_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, download_enabled BOOLEAN NOT NULL, watermark_enabled BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_472B783A7854B1FD ON gallery (access_code)');
        $this->addSql('CREATE INDEX IDX_472B783A19EB6921 ON gallery (client_id)');
        $this->addSql('ALTER TABLE gallery ADD CONSTRAINT FK_472B783A19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) NOT DEFERRABLE');

        $this->addSql('CREATE TABLE photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gallery_id INT NOT NULL, original_filename VARCHAR(255) NOT NULL, stored_filename VARCHAR(255) NOT NULL, path VARCHAR(500) NOT NULL, extension VARCHAR(10) DEFAULT NULL, file_size INT DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, caption VARCHAR(200) DEFAULT NULL, sort_order INT NOT NULL, is_featured BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_14B784184E7AF8F ON photo (gallery_id)');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B784184E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE photo DROP CONSTRAINT FK_14B784184E7AF8F');
        $this->addSql('ALTER TABLE gallery DROP CONSTRAINT FK_472B783A19EB6921');
        $this->addSql('DROP TABLE photo');
        $this->addSql('DROP TABLE gallery');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE "user"');
    }
}
